# Label to use when marking an issue as stale
staleLabel: stale

issues:
  markComment: >
    This issue has been automatically marked as stale because it has not had
    recent activity. You can comment on this (or do anything else) to keep it open,
    otherwise it'll be automatically closed in two week. Thanks!
  daysUntilStale: 90
  daysUntilClose: 14

pulls:
  markComment: >
    This PR hasn't been updated in a few weeks. Since this project can move quickly, 
    it probably has a bunch of merge conflicts and can't cleanly be merged in! 
    If this PR doesn't get updated within a week, it will be automatically closed.
    If that happens, feel free to open a new PR again with the same changes. Thanks!
  daysUntilStale: 14
  daysUntilClose: 7
