name: Generate documentation and deploy to GitHub wiki

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Build documentation
        run: ./generate_documentation.py
      - name: Upload Documentation to Wiki
        run: |
          git clone "https://${PAT}@${GITHUB_SERVER_URL#https://}/$GITHUB_REPOSITORY.wiki.git" wiki
          cd wiki
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          rm -rf docs
          cp -r ../docs .
          git add docs
          if git commit -m "Publish documentation to wiki" ; then
            git push
          fi
