
name: daily credits build

on:
  schedule:
    - cron: "5 0 * * *"

jobs:
  build_credits:
    runs-on: ubuntu-latest
    steps:
      - name: checkout latest code
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: cache credits
        id: cache-credits
        uses: actions/cache@v3.0.0
        with:
          key: credits-${{ steps.date.outputs.date }}
          path: credits.txt
      - name: update credits
        uses: actions/github-script@v3
        with:
          script: |
            const path = require('path');
            const script = require(path.resolve('.github/workflows/update-credits.js'));
            await script(github, context)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  